name: Docker Build - Dev Container
on:
  workflow_dispatch:
    inputs:
      no_cache:
        description: 'Use --no-cache flag for Docker build'
        required: false
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    # For biggish images, github actions runs out of disk space.

      - name: cleanup disk space
        run: sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Clear Docker cache if requested
        if: ${{ github.event.inputs.no_cache == 'true' }}
        run: docker system prune -a -f

      - name: Build the Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
            CACHE_BUSTER=""
            if [ "${{ github.event.inputs.no_cache }}" = "true" ]; then
              CACHE_BUSTER="--build-arg CACHE_BUSTER=$(date +%s)"
            fi

            docker build . \
            ${{ github.event.inputs.no_cache == 'true' && '--no-cache' || '' }} \
            $CACHE_BUSTER \
            --build-arg IS_DEVCONTAINER=true \
            --file .devcontainer/Dockerfile \
            --tag ghcr.io/avanscoyoc/non-avian-ml-toy/devcontainer:latest

      - name: Publish
        run: docker push ghcr.io/avanscoyoc/non-avian-ml-toy/devcontainer:latest